const NOTE_EVENTS = {
  ARROW_UP: 'ARROW_UP',
  ARROW_DOWN: 'ARROW_DOWN',
  ARROW_LEFT_AT_START: 'ARROW_LEFT_AT_START',
  ARROW_RIGHT_AT_END: 'ARROW_RIGHT_AT_END',
  ENTER_AT_START: 'ENTER_AT_START',
  ENTER_AT_END: 'ENTER_AT_END',
  ENTER_AT_POS: 'ENTER_AT_POS',
  BACKSPACE_AT_START_OF_EMPTY_LINE: 'BACKSPACE_AT_START_OF_EMPTY_LINE',
  BACKSPACE_AT_START_OF_NEMPTY_LINE: 'BACKSPACE_AT_START_OF_NEMPTY_LINE',
}

export default NOTE_EVENTS
