const NOTE_EVENTS = {
  ORDER_UP: 'ORDER_UP',
  ORDER_DOWN: 'ORDER_DOWN',
  ARROW_UP: 'ARROW_UP',
  ARROW_DOWN: 'ARROW_DOWN',
  ARROW_LEFT_AT_START: 'ARROW_LEFT_AT_START',
  ARROW_RIGHT_AT_END: 'ARROW_RIGHT_AT_END',
  MOVE_TO_START_OF_LINE: 'MOVE_TO_START_OF_LINE',
  MOVE_TO_END_OF_LINE: 'MOVE_TO_END_OF_LINE',
  ENTER_AT_START: 'ENTER_AT_START',
  ENTER_AT_END: 'ENTER_AT_END',
  ENTER_AT_POS: 'ENTER_AT_POS',
  BACKSPACE_AT_START_OF_EMPTY_LINE: 'BACKSPACE_AT_START_OF_EMPTY_LINE',
  BACKSPACE_AT_START_OF_NON_EMPTY_LINE: 'BACKSPACE_AT_START_OF_NON_EMPTY_LINE',
  TRASH_NOTE: 'TRASH_NOTE',
}

export default NOTE_EVENTS
